-- AlterTable
ALTER TABLE "HeroSection" ADD COLUMN     "logoHeight" INTEGER NOT NULL DEFAULT 280,
ADD COLUMN     "logoOpacity" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "logoVisible" BOOLEAN NOT NULL DEFAULT true;
